### PR TITLE
Toggle for critical and key products when creating Product Type

### PR DESCRIPTION
**Pull request by alexandrefilgueira**
This change allows to specify the following parameters when creating Product Types:
* critical_product
* key_product

The value is a boolean.

### CODE REVIEW

**Comment by jeffgran-dox** [comment]
Hi @alexandrefilgueira , thank you for this! The code looks good to me. I think maybe the tests are failing because the secrets are not available since it's running from a fork... or something. I will look at this more carefully and try to get it merged and released next week.

**Comment by alexandrefilgueira** [comment]
> Hi @alexandrefilgueira , thank you for this! The code looks good to me. I think maybe the tests are failing because the secrets are not available since it's running from a fork... or something. I will look at this more carefully and try to get it merged and released next week.

Perfect. I'll probably spend more time in some other improvements as in Neonomics we want to cover as many things as possible when configuring our DefectDojo instance through Terraform, so we would like to contribute more to this project.

I struggled a bit with what to define in the tests for this one, so let me know if I should consider something in particular

**Comment by jeffgran-dox** [comment]
> > 
> 
> Perfect. I'll probably spend more time in some other improvements as in Neonomics we want to cover as many things as possible when configuring our DefectDojo instance through Terraform, so we would like to contribute more to this project.

Sounds great! We will be happy to accept more additions. We just haven't needed any other resources (yet), but I tried to set this up so it makes it easy to add more.

> I struggled a bit with what to define in the tests for this one, so let me know if I should consider something in particular

Yes, a couple of things:
- in the data source tests: can we add a check for these two new fields? I think it would make sense to leave the new fields unspecified for one of the tests, and assert that they are defaulted to false when we pull the data source. And in the other one, set them to true, and assert that they are true in the data source.
- in the resource tests: for the third step, the "Update and Read testing" step, can we change the value from true->false or vice versa, and then assert the value has changed? similar to how we are updating the name/description and asserting that they changed.

**Comment by alexandrefilgueira** [comment]
I'm gonna need your help here. I'm not able to figure out what I'm doing wrong with the tests, but I always get (for example for the data test), that the new attributes are not found.
This is the simplest implementation of the several approaches I tried, based on what's already in those tests.

```
func TestAccProductTypeCriticalAndKeyChecksDataSource(t *testing.T) {
	name := fmt.Sprintf("dox-test-repo-%s", resource.UniqueId())
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create resource for testing datasource
			{
				Config: testAccProductTypeCriticalAndKeyChecksConfig(name),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.defectdojo_product_type.test", "name", name),
					resource.TestCheckResourceAttr("data.defectdojo_product_type.test", "description", "test"),
					resource.TestCheckResourceAttr("data.defectdojo_product_type.test", "critical_product", "false"),
					resource.TestCheckResourceAttr("data.defectdojo_product_type.test", "key_product", "false"),
				),
			},
		},
	})
}

func testAccProductTypeCriticalAndKeyChecksConfig(name string) string {
	return fmt.Sprintf(`
provider "defectdojo" {}
resource "defectdojo_product_type" "test" {
	name = %[1]q
	description = "test"
}
data "defectdojo_product_type" "test" {
	name = %[1]q
	depends_on = [defectdojo_product_type.test]
}
`, name)
}
```

This should create the resource with the default values assigned to those 2 new fields and then the check should verify that they are "false". Instead, I get:

> * Check 3/4 error: data.defectdojo_product_type.test: Attribute 'critical_product' not found
> * Check 4/4 error: data.defectdojo_product_type.test: Attribute 'key_product' not found

**Comment by jeffgran-dox** [comment]
Hey @alexandrefilgueira 

I took a closer look at your test, and I think it was just a real bug in the code! I made a test branch with your code and your test here: https://github.com/doximity/terraform-provider-defectdojo/pull/94/commits/6f62c5cb3120839cb437275432dbfb2dca0143d2#diff-522897ba47f759b6eaaaadcf4d9e4975df586348136674f831244259a8c54d3aR141-R142

A little more context: 

The `resource`s in this provider are set up with the metaprogramming/introspection to automatically do all the assigning from the api response to the terraform resource and vice versa, via the mapping set up with the go tags. So that's why there is no similar code to assign the data in the `product_type_resource` file.

And I made an initial attempt at setting up the data sources the same way where it would use a generic read function and do the assignment automatically. The problem is, for a data source, there's a lot of different ways those `GET`/read requests can work: for example in this data resource you can look up by id or by name. You could imagine other resources where you could even do a search with different search params, etc. So I could not think of a way to make this really generic, so for the data sources for now at least, we have to write the `read` api call manually, and assign the resulting data back to the underlying terraform resource object.

Hope that makes sense.

**Review by jeffgran-dox — APPROVED** [review]
LGTM

**Comment by jeffgran-dox** [comment]
@alexandrefilgueira I published v0.0.13-pre https://registry.terraform.io/providers/doximity/defectdojo/latest - would you mind validating for your use case and then I'll publish the real version?

**Comment by alexandrefilgueira** [comment]
Works as expected :)

**Pull request merged**
